package fullOne;

import java.time.ZonedDateTime;

/**
 * A DTO representing a visual timing.
 */
public class TransferTimingIndexDTO {

    private Long fileTransitionHistoryId;

    private Integer visualCount;

    private Integer somethingCount;

    private Integer transitionStateFromId;

    private Integer transitionStateToId;

    private Boolean transferStatus;

    private ZonedDateTime transferStartedAt;

    private ZonedDateTime transferEndedAt;

    private Long transferTimeSpentInSeconds;

    public TransferTimingIndexDTO() {

    }

    public TransferTimingIndexDTO(Long fileTransitionHistoryId, Integer visualCount, Integer somethingCount, Integer transitionStateFromId, Integer transitionStateToId, Boolean transferStatus, ZonedDateTime transferStartedAt, ZonedDateTime transferEndedAt, Long transferTimeSpentInSeconds) {
        this.fileTransitionHistoryId = fileTransitionHistoryId;
        this.visualCount = visualCount;
        this.somethingCount = somethingCount;
        this.transitionStateFromId = transitionStateFromId;
        this.transitionStateToId = transitionStateToId;
        this.transferStatus = transferStatus;
        this.transferStartedAt = transferStartedAt;
        this.transferEndedAt = transferEndedAt;
        this.transferTimeSpentInSeconds = transferTimeSpentInSeconds;
    }

    public Long getFileTransitionHistoryId() {
        return fileTransitionHistoryId;
    }

    public void setFileTransitionHistoryId(Long fileTransitionHistoryId) {
        this.fileTransitionHistoryId = fileTransitionHistoryId;
    }

    public Integer getVisualCount() {
        return visualCount;
    }

    public void setVisualCount(Integer visualCount) {
        this.visualCount = visualCount;
    }

    public Integer getSomethingCount() {
        return somethingCount;
    }

    public void setSomethingCount(Integer somethingCount) {
        this.somethingCount = somethingCount;
    }

    public Integer getTransitionStateFromId() {
        return transitionStateFromId;
    }

    public void setTransitionStateFromId(Integer transitionStateFromId) {
        this.transitionStateFromId = transitionStateFromId;
    }

    public Integer getTransitionStateToId() {
        return transitionStateToId;
    }

    public void setTransitionStateToId(Integer transitionStateToId) {
        this.transitionStateToId = transitionStateToId;
    }

    public Boolean getTransferStatus() {
        return transferStatus;
    }

    public void setTransferStatus(Boolean transferStatus) {
        this.transferStatus = transferStatus;
    }

    public ZonedDateTime getTransferStartedAt() {
        return transferStartedAt;
    }

    public void setTransferStartedAt(ZonedDateTime transferStartedAt) {
        this.transferStartedAt = transferStartedAt;
    }

    public ZonedDateTime getTransferEndedAt() {
        return transferEndedAt;
    }

    public void setTransferEndedAt(ZonedDateTime transferEndedAt) {
        this.transferEndedAt = transferEndedAt;
    }

    public Long getTransferTimeSpentInSeconds() {
        return transferTimeSpentInSeconds;
    }

    public void setTransferTimeSpentInSeconds(Long transferTimeSpentInSeconds) {
        this.transferTimeSpentInSeconds = transferTimeSpentInSeconds;
    }

    @Override
    public boolean equals(Object o) {
        // auto-generated by IntelliJ IDEA
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TransferTimingIndexDTO that = (TransferTimingIndexDTO) o;

        if (fileTransitionHistoryId != null ? !fileTransitionHistoryId.equals(that.fileTransitionHistoryId) : that.fileTransitionHistoryId != null)
            return false;
        if (visualCount != null ? !visualCount.equals(that.visualCount) : that.visualCount != null) return false;
        if (somethingCount != null ? !somethingCount.equals(that.somethingCount) : that.somethingCount != null)
            return false;
        if (transitionStateFromId != null ? !transitionStateFromId.equals(that.transitionStateFromId) : that.transitionStateFromId != null)
            return false;
        if (transitionStateToId != null ? !transitionStateToId.equals(that.transitionStateToId) : that.transitionStateToId != null)
            return false;
        if (transferStatus != null ? !transferStatus.equals(that.transferStatus) : that.transferStatus != null)
            return false;
        if (transferStartedAt != null ? !transferStartedAt.equals(that.transferStartedAt) : that.transferStartedAt != null)
            return false;
        if (transferEndedAt != null ? !transferEndedAt.equals(that.transferEndedAt) : that.transferEndedAt != null)
            return false;
        return transferTimeSpentInSeconds != null ? transferTimeSpentInSeconds.equals(that.transferTimeSpentInSeconds) : that.transferTimeSpentInSeconds == null;
    }

    @Override
    public int hashCode() {
        // auto-generated by IntelliJ IDEA
        int result = fileTransitionHistoryId != null ? fileTransitionHistoryId.hashCode() : 0;
        result = 31 * result + (visualCount != null ? visualCount.hashCode() : 0);
        result = 31 * result + (somethingCount != null ? somethingCount.hashCode() : 0);
        result = 31 * result + (transitionStateFromId != null ? transitionStateFromId.hashCode() : 0);
        result = 31 * result + (transitionStateToId != null ? transitionStateToId.hashCode() : 0);
        result = 31 * result + (transferStatus != null ? transferStatus.hashCode() : 0);
        result = 31 * result + (transferStartedAt != null ? transferStartedAt.hashCode() : 0);
        result = 31 * result + (transferEndedAt != null ? transferEndedAt.hashCode() : 0);
        result = 31 * result + (transferTimeSpentInSeconds != null ? transferTimeSpentInSeconds.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        // auto-generated by IntelliJ IDEA
        return "TransferTimingIndexDTO{" +
            "fileTransitionHistoryId=" + fileTransitionHistoryId +
            ", visualCount=" + visualCount +
            ", somethingCount=" + somethingCount +
            ", transitionStateFromId=" + transitionStateFromId +
            ", transitionStateToId=" + transitionStateToId +
            ", transferStatus=" + transferStatus +
            ", transferStartedAt=" + transferStartedAt +
            ", transferEndedAt=" + transferEndedAt +
            ", transferTimeSpentInSeconds=" + transferTimeSpentInSeconds +
            '}';
    }
}
